---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
    driver:
      customize:
        cpus: 4
        memory: 6144
      synced_folders:
        - ["cache", "/root/cache", "create: true"]

suites:
  - name: default
    run_list:
      - recipe[diskimage-builder-env::default]
    attributes:
