#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIB_CLOUD_INIT_DATASOURCES=${DIB_CLOUD_INIT_DATASOURCES:-""}
DIB_CLOUD_INIT_CONFIG=${DIB_CLOUD_INIT_CONFIG:-""}

if [ -z "$DIB_CLOUD_INIT_DATASOURCES" ] && [ -z "$DIB_CLOUD_INIT_CONFIG" ] ; then
  echo "DIB_CLOUD_INIT_DATASOURCES must be set to a comma-separated list "
  echo "of cloud-init data sources you wish to use, ie 'Ec2, NoCloud, ConfigDrive'"
  exit 1
fi

if [ -d /etc/cloud/cloud.cfg.d ]; then
  if [ ! -z "$DIB_CLOUD_INIT_DATASOURCES" ] && [ -z "$DIB_CLOUD_INIT_CONFIG" ] ; then
    # DatasourceNone doesn't exist in Ubuntu 12.04 (Precise)
    # which uses cloud-init version 0.6.3
    if [ "$(lsb_release -cs)" = 'precise' ] ; then
        cat > /etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg <<EOF
datasource_list: [  $DIB_CLOUD_INIT_DATASOURCES ]
EOF
    else
        cat > /etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg <<EOF
datasource_list: [  $DIB_CLOUD_INIT_DATASOURCES, None ]
EOF
    fi
  fi

  if [ ! -z "$DIB_CLOUD_INIT_CONFIG" ] ; then
    echo "$DIB_CLOUD_INIT_CONFIG" > /etc/cloud/cloud.cfg.d/91-dib-cloud-init-datasources.cfg
  fi
fi
